import os
import re
from fpdf import FPDF

class DeVanaPDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 8)
        self.cell(0, 10, "DeVana: Dynamic Vibration Absorber Optimization Framework - Sovereign Documentation", align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")

def clean_markdown(text):
    # Map common Unicode characters to ASCII equivalents
    replacements = {
        "\u2013": "-", # en-dash
        "\u2014": "--", # em-dash
        "\u2248": "~=", # almost equal to
        "\u221e": "INF", # infinity
        "\u03bc": "mu", # greek mu
        "\u03b6": "zeta", # greek zeta
        "\u03c9": "omega", # greek omega
        "\u03bb": "lambda", # greek lambda
        "\u03bd": "nu", # greek nu
        "\u03b1": "alpha", # greek alpha
        "\u03b2": "beta", # greek beta
        "\u03c4": "tau", # greek tau
        "\u2202": "delta", # partial differential
        "\u2206": "Delta", # increment
        "\u2211": "SUM", # n-ary summation
        "\u2207": "grad", # nabla
        "\u22c5": "*", # dot operator
        "\u2264": "<=", # less-than or equal to
        "\u2265": ">=", # greater-than or equal to
        "\u03a9": "Omega", # greek capital omega
        "\u00b1": "+/-", # plus-minus
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
        
    # Remove Mermaid blocks for PDF
    text = re.sub(r"```mermaid.*?```", "[Mermaid Flowchart - See Pseudo-code below]", text, flags=re.DOTALL)
    
    # Strip non-latin1 characters as a final safety measure
    text = "".join(c if ord(c) < 256 else "?" for c in text)
    
    return text

def create_pdf():
    pdf = DeVanaPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.alias_nb_pages()
    
    # Priority Order
    files_to_include = [
        "Documents/INDEX.md",
        "Documents/Optimization_Guild/README.md",
        "Documents/GUI_Guild/README.md",
        "Documents/API_Library_Guild/README.md",
        "Documents/Physics_Guild/README.md",
    ]
    
    # Discovery
    all_files = []
    for root, dirs, files in os.walk("Documents"):
        for file in files:
            if file.endswith(".md"):
                all_files.append(os.path.join(root, file))
    
    # Ensure priority files are first, then the rest
    final_list = [f for f in files_to_include if os.path.exists(f)]
    remaining = [f for f in all_files if f not in final_list]
    final_list.extend(sorted(remaining))

    # Add Title Page
    pdf.add_page()
    pdf.set_font("helvetica", "B", 24)
    pdf.ln(80)
    pdf.cell(0, 20, "DeVana", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "B", 16)
    pdf.cell(0, 10, "Dynamic Vibration Absorber Optimization Framework", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 10, "Sovereign Hyper-Exhaustive Documentation", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, "Generated by Dolores Guild", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(20)
    pdf.cell(0, 10, "Date: June 7, 2026", align="C", new_x="LMARGIN", new_y="NEXT")

    for file_path in final_list:
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            
            content = clean_markdown(content)
            
            pdf.add_page()
            pdf.set_font("helvetica", "B", 14)
            pdf.set_fill_color(240, 240, 240)
            pdf.cell(0, 10, f"FILE: {file_path}", fill=True, new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)
            
            pdf.set_font("helvetica", "", 10)
            pdf.multi_cell(0, 5, content)
            
        except Exception as e:
            print(f"Error processing {file_path}: {e}")

    output_name = "DeVana_Sovereign_Documentation.pdf"
    pdf.output(output_name)
    print(f"Successfully generated {output_name}")

if __name__ == "__main__":
    create_pdf()
